spring:
  application:
    name: howmeet
  config:
    import:
      - classpath:/yaml/application-auth.yml
      - classpath:/yaml/application-db.yml
      - classpath:/yaml/application-oauth.yml
  profiles:
    group:
      develop: auth, db, oauth
    active: develop
